config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  # resources :projects
  resources :posts
  root 'posts#index'

# get '/posts' => 'post#index'
# get '/posts/:id' => 'post#show', as: 'post'
# get '/posts/:id/new' => 'post#new', as: 'new_post'

  

  # scope module :admin do
  #   resources :posts
  # end

# FOR ADMIN/ARTICLES
    
    #    resources :articles
    #    root 'articles#index'
    
    namespace :admin do
      resources :articles  
    end

    # scope module: 'admin' do
    #   resources :articles
    # end

    # resources :articles

    # scope '/admin' do
    #   resources :articles
    # end

  end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
    has_and_belongs_to_many :students
end

app/models/department.rb
class Department < ApplicationRecord
has_one :manager
has_one :manager_history, through: :manager
end

app/models/dummy.rb
class Dummy < ApplicationRecord
    has_one :sub_demo

    before_create :greeting_message

    def greeting_message
        puts 'I am called before object create!'
    end
end

app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :department
  has_one :manager_history
end

app/models/manager_history.rb
class ManagerHistory < ApplicationRecord
  belongs_to :manager
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :student, optional: true

    validates :title, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :student_projects
    has_many :students, through: :student_projects
end

app/models/student.rb
class Student < ApplicationRecord
has_many :posts 
has_and_belongs_to_many :courses
has_many :student_projects
has_many :projects, through: :student_projects

validates :name, presence: true
validates :email, presence: true, uniqueness: true
validates :name, length: {minimum:2, maximum:50}
validates :name, format: { with: /\A[a-zA-Z]+\z/, message: 'Only letters are allowed' }

validate :validate_student_age

after_create :display_student_age

def display_student_age
    if self.date_of_birth.present?
        age = Date.today.year - self.date_of_birth.year
        puts "========Age of student is #{age}=========="
    else
        puts "============date cannot be calculated without the date_of_birth============"
    end
    end
end

def validate_student_age
    if self.date_of_birth.present?
        age = Date.today.year - self.date_of_birth.year
            if age < 15
                errors.add(:age, 'Please provide valid date of birth here. Age must be greater than 15')
            end
    end
end

app/models/student_project.rb
class StudentProject < ApplicationRecord
  belongs_to :student
  belongs_to :project
end

app/models/sub_demo.rb
class SubDemo < ApplicationRecord
  belongs_to :dummy
end

app/controllers/admin/articles_controller.rb
module Admin
    class ArticlesController < ::ArticlesController
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    before_action :find_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(post_params)
    if @article.save
      redirect_to admin_article_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    
    if @article.update(post_params)
      redirect_to admin_article_path
    else
      render 'edit'
    end

  end

  def destroy
    @article.destroy
    redirect_to root_path
  end

  private 

  def find_article
    @article = Article.find(params[:id])
  end

  def post_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts=Post.order("created_at DESC")
  end

  def new
    @post=Post.new
  end

  def create
    @post=Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end

  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private 

  def find_post
    @post=Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/articles/_form.html.erb
<%= form_for [:admin, @article] do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
    <br>
    <%= f.label :body %><br>
    <%= f.text_area :body %><br>
    <br>
    <%= f.submit %>

    <% end %>

app/views/admin/articles/edit.html.erb
<h1>This is admin/article EDIT page</h1>

<h1>Edit Article</h1>

<%= render 'form' %>

app/views/admin/articles/index.html.erb
<h1>This is admin/article index page</h1>


<% @articles.each do |article| %>
    <h2><%= article.title %> </h2>
    <div><%= truncate(article.body, :length => 35) %></div>
    <br>
    <%= link_to "Read Article", @article_admin%>
    <hr>

<% end %>

app/views/admin/articles/show.html.erb
<h1>_Namespace and _Scope_Module admin/article show page </h1>

<h1><%= @article.title %></h1>

<div>
<%= @article.body %>
</div>
<br>
<%= link_to 'Edit Article', edit_admin_article_path(@article) %>
<br>
<%= link_to 'Delete Article', admin_article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/articles/_form.html.erb
<%= form_for [@article] do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
    <br>
    <%= f.label :body %><br>
    <%= f.text_area :body %><br>
    <br>
    <%= f.submit %>

    <% end %>
    

app/views/articles/edit.html.erb
<h1>this is EDIT page articles</h1>

<h1>Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>this is index page articles</h1>

<% @articles.each do |article| %>
    <h2><%= link_to article.title, article %> </h2>
    <div><%= truncate(article.body, :length => 35) %></div>
    <br>
    <%= link_to "Read Article", article %>
    <hr>
<% end %>

app/views/articles/new.html.erb
<h1>this is New page articles</h1>

<h1>New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>This is _Scope show page article</h1>

<h1><%= @article.title %></h1>

<div>
<%= @article.body %>
</div>
<br>
<%= link_to 'Edit Article', edit_article_path(@article) %>
<br>
<%= link_to 'Delete Article', article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
    <br>
    <%= f.label :body %><br>
    <%= f.text_area :body %><br>
    <br>
    <%= f.submit %>

    <% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
    <h2><%= link_to post.title, post %> </h2>
    <div><%= truncate(post.body, :length => 35) %></div>
    <br>
    <%= link_to "Read Post", post %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<div>
<%= @post.body %>
</div>
<br>
<%= link_to 'Edit Post', edit_post_path(@post) %>
<br>
<%= link_to 'Delete Post', post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>